### ISSUE TITLE
called every time a template is re-created

### ISSUE THREAD

**Issue by dcsan** [ivanbrykov/meteor-multiple-callbacks#1]
looks like a neat package.

question:

if i have a number of pages that use the same template, but just different data,
does the "rendered" callback get called?

for example a blog where i want to trigger an animation on each article.

with using IronRouter i found the events are only triggered when you move between different templates...

**Comment by ivanbrykov** [comment]
Look, this package is just an intermediate layer between the app and Meteor API. So whenever Meteor triggers `rendered` callback for a template all callbacks attached to it using `Template.rendered()` will trigger as well. 

According to my understanding, Meteor triggers `rendered` event whenever new occurrence of a template is instantiated and attached to the page. E.g. you have a list of 3 blog posts and display them on one page in the loop via the template `blogPost`. So I presume, `rendered` event will be issued 3 times for one template `blogPost`.
