### ISSUE TITLE
Did Meteor 0.8.3 break it?

### ISSUE THREAD

**Issue by Lepozepo** [ivanbrykov/meteor-multiple-callbacks#2]
This package is the best! Did it break with the latest update?

**Comment by ivanbrykov** [comment]
Thanks!

It seems it does. Will check it.

**Comment by ivanbrykov** [comment]
Just [pushed an update](https://github.com/brykov/meteor-multiple-callbacks/commit/a204aaed85539e7692926b0d09708bc55a836630) tagged as v0.1.3 that seems to solve the problem. 

Thanks for noticing!

**Comment by Lepozepo** [comment]
Thank you!
