### ISSUE TITLE
Seems like it's broken after update to 0.9.1

### ISSUE THREAD

**Issue by ghost** [ivanbrykov/meteor-multiple-callbacks#3]
Template is a function from now on.

**Comment by ivanbrykov** [comment]
It was a function before, too. But something has changed and _.each cannot iterate over Template's properties anymore. I have published an update, try it.

**Comment by ghost** [comment]
Actually it was an object
_.each has some checks for the argument and 'length is integer' is true for the function. It also has a length but it is a number of arguments for the function. For..in works good in this case.
Update works. Thanks
